import numpy as np 
a=np.arange(9,dtype=np.float).reshape(3,3)
print('frist array')
print(a)
print('second array')
b=np.array([10,10,10])
print(b)
print('add the two array')
print(np.add(a,b))
print('subtract the two array')
print(np.subtract(a,b))
print('multiply the two array')
print(np.multiply(a,b))
print('divide the two arrays')
print(np.divide(a,b))
print('dot product two array')
print(np.dot(a,b))